RetroRabbit/RGO-Client

src/app/components/hris/employees/new-employee/new-employee.component.html
=> fixing starterkit icons

src/app/components/hris/employees/view-employee/view-employee.component.css
the search bar no longer breaks when tabbing between employees and back
=> removed what was affecting the searchbar

src/app/components/hris/employees/employee-profile/accordions/accordion-employee-documents/accordion-employee-documents.component.html, src/app/components/hris/employees/employee-profile/accordions/accordion-employee-documents/accordion-employee-documents.component.ts
Display confirm dialog when the user needs to update a document
=> Confirm dialog employee documents accordion

src/app/components/hris/employees/employee-profile/accordions/accordion-banking/accordion-banking.component.ts, src/app/components/hris/employees/employee-profile/accordions/accordion-profile/accordion-profile-additional-details/accordion-profile-additional.component.ts, src/app/components/hris/employees/employee-profile/accordions/accordion-profile/accordion-profile-address-details/accordion-profile-address-details.component.ts, src/app/components/hris/employees/employee-profile/accordions/accordion-profile/accordion-profile-contact-details/accordion-profile-contact-details.component.ts, src/app/components/hris/employees/employee-profile/accordions/accordion-profile/accordion-profile-employee-details/accordion-profile-employee-details.component.ts, src/app/components/hris/employees/employee-profile/accordions/accordion-profile/accordion-profile-personal-details/accordion-profile-personal-details.component.ts, src/app/components/hris/employees/employee-profile/employee-profile.component.html, src/app/components/hris/nav-bar/types/side-nav/side-nav.component.ts
These changes ensure proper data handling and improve the robustness of the employee profile view, addressing the bug where profile data was not being fetched correctly.
**1. File Existence Check**
Updated the condition to check for file existence using a more concise approach.
**2. Property Permissions Check**
Added a guard clause to ensure accessProperties is available before proceeding.
**3. Conditional Rendering Update**
Simplified and corrected the conditional rendering logic to handle null checks for employeeProfile and selectedEmployee.
=> Bug 8964 Employee view does not fetch profile data

src/app/components/hris/custom-fields/save-custom-field/save-custom-field.component.css, src/app/components/hris/custom-fields/save-custom-field/save-custom-field.component.html, src/app/components/hris/custom-fields/save-custom-field/save-custom-field.component.ts
Description: Implemented a fix for the custom field page to scale down on mobile devices.
Desktop view:
Mobile view:
=> Bug 8579 Custom Field Page not scaling down

src/app/components/hris/custom-fields/save-custom-field/save-custom-field.component.html, src/app/components/hris/custom-fields/save-custom-field/save-custom-field.component.ts, src/app/components/hris/employees/employee-profile/accordions/accordion-documents/accordion-additional-documents/accordion-additional-documents.component.css, src/app/components/hris/employees/employee-profile/accordions/accordion-documents/accordion-additional-documents/accordion-additional-documents.component.html, src/app/components/hris/employees/employee-profile/accordions/accordion-documents/accordion-additional-documents/accordion-additional-documents.component.ts, src/app/components/hris/employees/employee-profile/employee-profile.component.html, src/app/components/hris/employees/employee-profile/shared-accordion-functionality.ts
Description: Upload and download functionality of additional documents accordion and empty state for additional documents implemented. Disable/Enable save button for custom fields implemented. Screenshots provided below:
**Empty State for custom documents:**
**Disabled save button when radio buttons are not checked**
**Custom fields everything filled**
**File Upload Popup**
**File is selected and appears**
**File Downloads**
**File Updates**
=> Upload and Download Functionality of Additional documents Accordion.

src/app/components/hris/nav-bar/types/side-nav/side-nav.component.ts
Changed the wrong auth access to look for the correct roles instead of !employee role
Bug Ticket: [9041](https://dev.azure.com/retro-rabbit/RetroGradOnboard/_workitems/edit/9041)
=> Fixed employee number no showing

src/app/components/hris/employees/employee-options/employee-options.component.html, src/app/components/hris/employees/employee-options/employee-options.component.ts
Description: Hide the side navigation bar from Journey.
See screenshot below before changes were made:
See screenshot below after hiding the side navigation bar:
=> Hide Employee Approvals From Journey

src/app/components/hris/employees/employee-profile/accordions/accordion-career-summary/accordion-certificates/accordion-certificates.component.ts
added snackbar on upload and re upload
=> added some snackbars for upload

src/app/components/hris/employees/employee-profile/employee-profile.component.html, src/app/components/hris/employees/employee-profile/employee-profile.component.ts, src/app/services/shared-services/nav-service/nav.service.ts
Added the true to the isHRIS value
=> Fixed Profile Tab not sowing

src/app/components/hris/employees/employee-profile/employee-profile.component.html, src/app/components/hris/employees/employee-profile/employee-profile.component.ts, src/app/models/hris/employee-address.interface.ts
fixed based in to display only when there is data
=> added fix for based in

src/app/components/hris/employees/employee-approvals/employee-approvals.component.css, src/app/components/hris/employees/employee-approvals/employee-approvals.component.html, src/app/components/hris/employees/employee-profile/accordions/accordion-career-summary/accordion-career-work-experience/accordion-career-work-experience.component.ts, src/app/components/hris/employees/view-employee/view-employee.component.css, src/app/components/hris/employees/view-employee/view-employee.component.html
**Empty states for Employee search and Approvals section:**
- Approvals section all tabs empty states are the same
- _Also removed a console log from my previous accordion that was forgotten_
=> Updated empty states for Employee search and Approvals

src/app/components/hris/employees/view-employee/view-employee.component.css, src/app/components/hris/employees/view-employee/view-employee.component.html
Fixed alignment being overwritten
=> HOTFIX for alignment

src/app/components/hris/employees/employee-profile/accordions/accordion-career-summary/accordion-salary-details/accordion-salary-details.component.ts
https://drive.google.com/drive/folders/1k2YiblPGEibTDfutmTCrhwGo8-0W1yV0?usp=sharing
=> Fixing remuneration Bug

src/app/components/hris/employees/employee-profile/accordions/accordion-career-summary/accordion-salary-details/accordion-salary-details.component.ts
**Ticket details:** 
- Snack bar info doesnt make sense
- Updated Info:
=> Snackbar update

src/app/components/hris/employees/employee-profile/accordions/accordion-career-summary/accordion-career-work-experience/accordion-career-work-experience.component.html, src/app/components/hris/employees/employee-profile/accordions/accordion-career-summary/accordion-career-work-experience/accordion-career-work-experience.component.ts
- **Ticket details:**
- **Implementation:**
=> Work experience added and formatted the date according to design

src/app/components/hris/employees/new-employee/new-employee.component.html
Description: Set the default country to South Africa in the drop down list.
Added the asterisk (*) to indicate required input field
=> Set default country to South Afrca

src/app/app.component.html
=> Employee profile photo fix

src/app/components/hris/employees/new-employee/new-employee.component.ts
- Added a check to make us of the existing id validation the form now will not submit if the id number is not validated fully.
- Fixed the previous bug that allowed you to create a employee even if the id is not valid
=> added check for id validation

src/app/components/hris/employees/employee-profile/accordions/accordion-career-summary/accordion-career-summary-qualifications/accordion-career-summary-qualifications.component.ts, src/app/components/hris/employees/employee-profile/accordions/accordion-profile/accordion-profile-employee-details/accordion-profile-employee-details.component.html, src/app/components/hris/employees/employee-profile/shared-accordion-functionality.ts
Description: Fixed Employee Details **Missing Information Error** for required fields
=> Missing Information on Employee Details Accordion

src/app/models/hris/constants/documents.contants.ts
Renamed Fixed Term Contact to Retro Rabbit Employment Contract on the UI
=> Renamed Fixed Term Contracts on Starter Kit Documents

src/app/components/hris/sign-in/sign-in.component.ts, src/app/services/shared-services/auth-access/auth.service.ts
A solution provided for when a user is created in the database but does not exist yet in Auth0.
[Backend changes](https://github.com/RetroRabbit/RGO-Server/pull/155)
https://github.com/RetroRabbit/RGO-Client/assets/68727050/b93dd0e6-ef86-4154-8427-cdf23332e3fc
https://github.com/RetroRabbit/RGO-Client/assets/68727050/e74083b7-7a7c-41db-9550-0f8ef0daf9c4
[Bug 9524](https://dev.azure.com/retro-rabbit/RetroGradOnboard/_sprints/backlog/RetroGradOnboard%20Team/RetroGradOnboard/Sprint%2023?workitem=9524)
=> DEV | Sort out flow of login

src/app/app.component.css, src/app/components/hris/employees/employee-profile/accordions/accordion-profile/accordion-career-additional-information/accordion-career-additional-information.component.ts, src/app/components/hris/employees/employee-profile/shared-accordion-functionality.ts
now shows 0% when nothing has been filled in
Added a styling fix for white bar showing on the add field options form
=> Juanro/career summary percentage fix showing NaN

src/app/components/hris/employees/employee-profile/accordions/accordion-profile/accordion-career-additional-information/accordion-career-additional-information.component.html, src/app/components/hris/employees/employee-profile/accordions/accordion-profile/accordion-profile-additional-details/accordion-profile-additional.component.html
=> Fix edit button

src/app/components/hris/employees/employee-profile/employee-profile.component.html, src/app/components/hris/employees/new-employee/new-employee.component.html, src/app/components/hris/employees/new-employee/new-employee.component.ts
**_Various Bug fixes to be done on the add new employee form:_**
1. **Role dropdown validated and functioning:**
2. **Validation added for the disabilities option. If you say yes you need to add disability notes before you can submit the form**
3. **Profile image can only png, jpg/jpeg and less than 4mb**
4. **Email copy to clipboard is now applied to entire pill not just the Icon**
=> Updated Add Employee Form

src/app/components/hris/employees/employee-profile/shared-accordion-functionality.ts
Description: Added a check for required fields to fix the missing information issue on additional information accordion. 
Before the fix (Degree is not a required field):
After:
=> Fixed Missing Information on Additional Information Accordion

src/app/components/hris/employees/employee-profile/accordions/accordion-career-summary/accordion-salary-details/accordion-salary-details.component.html, src/app/components/hris/employees/employee-profile/accordions/accordion-career-summary/accordion-salary-details/accordion-salary-details.component.ts, src/app/components/hris/employees/employee-profile/accordions/accordion-profile/accordion-profile-personal-details/accordion-profile-personal-details.component.html, src/app/components/hris/employees/employee-profile/accordions/accordion-profile/accordion-profile-personal-details/accordion-profile-personal-details.component.ts, src/app/components/hris/employees/employee-profile/shared-accordion-functionality.ts
Added fields to Accordions:
**Personal details:**
- countryOfBirth
- Nationality
**Salary Details:**
- Tax Number
=> Adding fields to Accordions

src/app/components/hris/system-settings/property-access/property-access.component.html, src/app/components/hris/system-settings/property-access/property-access.component.ts
Improve the filter for Property Access Management to allow the table to be sorted by Role.
https://drive.google.com/file/d/1Xx6PytfzCsov2CUTtoQtbVQpNE136Fo0/view?usp=drive_link
=> Added sorting method to improve table filter

src/app/components/ats/candidates/new-candidate/new-candidate.component.ts, src/app/components/hris/employees/employee-profile/shared-accordion-functionality.ts, src/app/components/hris/employees/new-employee/new-employee.component.ts
=> fixed race validation

src/app/components/hris/employees/employee-profile/accordions/accordion-career-summary/accordion-salary-details/accordion-salary-details.component.html, src/app/components/hris/employees/employee-profile/accordions/accordion-career-summary/accordion-salary-details/accordion-salary-details.component.ts, src/app/components/hris/employees/employee-profile/accordions/accordion-profile/accordion-profile-personal-details/accordion-profile-personal-details.component.html, src/app/components/hris/employees/employee-profile/accordions/accordion-profile/accordion-profile-personal-details/accordion-profile-personal-details.component.ts
**Fixed fields for Country of Birth and Nationality:**
**Fixed validation for Tax Number:**
**If tax number is does not start with 0, 1, 2, 3, or 9.**
**If tax number is more than 9 numbers:**
=> Fix Fields

src/app/components/hris/cv-document/cv-document.component.ts, src/app/components/hris/employees/employee-profile/accordions/accordion-profile/accordion-profile-personal-details/accordion-profile-personal-details.component.html, src/app/components/hris/employees/employee-profile/accordions/accordion-profile/accordion-profile-personal-details/accordion-profile-personal-details.component.ts, src/app/components/hris/employees/employee-profile/employee-profile.component.css, src/app/components/hris/employees/employee-profile/shared-accordion-functionality.ts, src/app/components/hris/employees/new-employee/new-employee.component.html, src/app/components/hris/employees/new-employee/new-employee.component.ts, src/app/components/hris/employees/view-employee/view-employee.component.ts, src/app/models/hris/employee-profile.interface.ts
=> disability type added

src/app/components/hris/employees/view-employee/view-employee.component.html
=> updated names on employee table filter

src/app/components/hris/employees/employee-profile/accordions/accordion-documents/accordion-additional-documents/accordion-additional-documents.component.ts, src/app/components/hris/employees/employee-profile/accordions/accordion-profile/accordion-profile-additional-details/accordion-profile-additional.component.html, src/app/components/hris/employees/employee-profile/accordions/accordion-profile/accordion-profile-additional-details/accordion-profile-additional.component.ts
**When custom fields are archived on system settings they will not show on additional fields**
No Archived Items:
=> Archived Custom Fields for Additional Information

src/app/components/hris/employees/employee-profile/accordions/accordion-profile/accordion-profile-contact-details/accordion-profile-contact-details.component.html, src/app/components/hris/employees/employee-profile/accordions/accordion-profile/accordion-profile-contact-details/accordion-profile-contact-details.component.ts
- Fixed regex to prevent letters in numbers field
- Fixed casing and labels
=> fixed casing and regex

src/app/components/hris/employees/employee-profile/accordions/accordion-banking/accordion-banking.component.ts
=> banking fixed

src/app/components/hris/employees/employee-profile/employee-profile.component.css, src/styles.css
- Fixed color and border radius in progressbar
- confirmed colors and styling with wouter
=> Juanro/fix progressbar UI

src/app/components/ats/candidates/new-candidate/new-candidate.component.html, src/app/components/hris/custom-fields/manage-field-code/manage-field-code.component.ts, src/app/components/hris/employees/employee-profile/accordions/accordion-career-summary/accordion-career-work-experience/accordion-career-work-experience.component.ts, src/app/components/hris/employees/employee-profile/accordions/accordion-career-summary/accordion-certificates/accordion-certificates.component.ts, src/app/components/hris/employees/new-employee/new-employee.component.html
=> Modal Title Casing on Modal and Validations

src/app/components/hris/admin-dashboard/admin-dashboard.component.ts
- Logged in users charts now get fetched on first load no more hanging
=> fixed id not being fetched

src/app/components/hris/employees/employee-profile/accordions/accordion-profile/accordion-profile-personal-details/accordion-profile-personal-details.component.ts
https://github.com/user-attachments/assets/1bde3aeb-50eb-4edf-ba99-96eaa31e9bed
=> displays correctly on first load.

src/app/components/hris/employees/employee-profile/accordions/accordion-career-summary/accordion-certificates/accordion-certificates.component.html, src/app/components/hris/employees/new-employee/new-employee.component.html, src/app/components/hris/employees/new-employee/new-employee.component.ts
- labels now have correct camel case
- Updated cellphone number field to have correct casing and text
- updated error message
=> updated sentance case

src/app/components/hris/employees/employee-profile/accordions/accordion-profile/accordion-profile-contact-details/accordion-profile-contact-details.component.ts
Fixed the form control for contact details and adjusted styling to be more consistent among the phone number form input fields.
=> Fixed form control

src/app/components/hris/employees/employee-profile/accordions/accordion-profile/accordion-profile-contact-details/accordion-profile-contact-details.component.ts
**The employee Contact details are saving:**
=> Contact form save fix and format

src/app/components/hris/employees/new-employee/new-employee.component.html, src/app/components/hris/employees/new-employee/new-employee.component.ts
https://drive.google.com/file/d/16P3FcDnCVLgj6ZdbOBa47IGl5X6OrRS1/view?usp=sharing
Employee Journey Refactored
Employee will only be saved when "Save" or "Save and Add another" is clicked. The documents now also only upload after the employee has been saved. Back button goes back to filled in form and add another clears the form. Other bug ticket for clearing and validation is still active. I can't get the cellphone number field to clear data.
=> employee basically working

src/app/components/hris/sign-in/sign-in.component.ts
Overview:
Currently:
1) Only retrorabbit.co.za org. accounts can login as per normal.
2) If account does not exist in Db, in gets deleted in auth0
3) If account exists in Db but not in auth0, then account is finalized (snack-bar)
Update:
4) If account exist in auth0 with or without a role but not in Db, meaning someone manually deleted their account in Db then they wont be allowed to login.
=> System | If you do not have a profile in the DB, it should not let you sign in

src/app/components/hris/employees/employee-profile/accordions/accordion-career-summary/accordion-career-summary-qualifications/accordion-career-summary-qualifications.component.ts
Update for qualification was not working.
https://drive.google.com/file/d/1ZLdJWibSiMFWc0HVc4zknhlDqftL2Jeu/view?usp=sharing
=> Fixed Employee Qualification not updating

src/app/components/hris/cv-document/cv-document.component.ts, src/app/components/hris/employees/employee-profile/accordions/accordion-profile/accordion-profile-personal-details/accordion-profile-personal-details.component.css, src/app/components/hris/employees/employee-profile/accordions/accordion-profile/accordion-profile-personal-details/accordion-profile-personal-details.component.html, src/app/components/hris/employees/employee-profile/accordions/accordion-profile/accordion-profile-personal-details/accordion-profile-personal-details.component.ts
Disability Type works Like expected. 
https://drive.google.com/file/d/1f4bFFVEXrKLqY80Vl7a_5QXcLg42LMCy/view?usp=sharing
=> Disability type working as expected and clean up

src/app/components/hris/employees/employee-profile/accordions/accordion-career-summary/accordion-career-work-experience/accordion-career-work-experience.component.css
=> Fixed Project description Box Sizing

src/app/components/ats/candidates/new-candidate/new-candidate.component.html, src/app/components/hris/employees/employee-profile/accordions/accordion-career-summary/accordion-career-work-experience/accordion-career-work-experience.component.ts, src/app/components/hris/employees/employee-profile/accordions/accordion-career-summary/accordion-certificates/accordion-certificates.component.ts, src/app/components/hris/employees/new-employee/new-employee.component.html
=> Sentence case on error messages

src/app/components/hris/employees/new-employee/new-employee.component.html, src/app/components/hris/employees/new-employee/new-employee.component.ts
Description: Added error messages for required Role, Level and ID Number. 
Validation: 
Save Employee:
https://drive.google.com/file/d/1xXvqWusCLHOQYlrPkjLjbX4kynyxH7pl/view?usp=sharing
=> Fix validation on Add New Employee

src/app/app.module.ts, src/app/components/hris/employees/employee-details/employee-details.component.ts, src/app/components/hris/employees/employee-profile/accordions/accordion-profile/accordion-career-additional-information/accordion-career-additional-information.component.ts, src/app/components/hris/employees/employee-profile/accordions/accordion-profile/accordion-profile-additional-details/accordion-profile-additional.component.ts, src/app/components/hris/employees/employee-profile/accordions/accordion-profile/accordion-profile-address-details/accordion-profile-address-details.component.ts, src/app/components/hris/employees/employee-profile/accordions/accordion-profile/accordion-profile-employee-details/accordion-profile-employee-details.component.ts, src/app/components/hris/employees/employee-profile/employee-profile.component.ts, src/app/components/hris/sign-in/sign-in.component.ts, src/app/components/shared-components/interceptor/auth0.interceptor.ts, src/app/components/shared-components/store/actions/client.actions.ts, src/app/components/shared-components/store/actions/sign-in.actions.ts, src/app/components/shared-components/store/app.state.ts, src/app/components/shared-components/store/effects/client.effects.ts, src/app/components/shared-components/store/effects/sign-in.effects.ts, src/app/components/shared-components/store/reducers/client.reducer.ts, src/app/components/shared-components/store/reducers/sign-in.reducer.ts, src/app/components/shared-components/store/selector/client.selector.ts, src/app/components/shared-components/store/selector/sign-in.selector.ts, src/app/services/shared-services/auth-access/auth-access.service.ts, src/app/services/shared-services/store-service/store-access.service.ts
Implemented ngrx for getAllClients request.
Fixed naming convention to make code more readable.
=> FE | Reduce requests calls for clients endpoint
