RetroRabbit/RGO-Client

src/app/components/hris/employees/employee-profile/accordions/accordion-profile/accordion-profile-address-details/accordion-profile-address-details.component.ts

Errors no longer gets thrown to the console, if the accordion has no data
Accordions API calls still works as intended when data has been entered.

Prevent API call from happening if there is no data for the country

---

src/app/components/hris/sign-in/sign-in.component.ts
src/app/services/shared-services/nav-service/nav.service.ts

Implemented token validation and enhanced cookie security.
**Problem**
This pull request proposes a potential solution for addressing the issue where the Employee Role gets logged out after logging in.
This problem may arise due to the rejection of HttpOnly cookies when using TLS. By implementing the suggested changes, we aim to mitigate this issue and ensure smoother authentication experiences for users with the Employee Role.
[Bug 8899](https://dev.azure.com/retro-rabbit/RetroGradOnboard/_sprints/taskboard/RetroGradOnboard%20Team/RetroGradOnboard/Sprint%2021?workitem=8899)

Bug 8899 | Users with "Employee" Role get's logged out immediately

---

src/app/components/hris/custom-fields/save-custom-field/save-custom-field.component.html
src/app/components/hris/custom-fields/save-custom-field/save-custom-field.component.ts
src/app/models/hris/constants/types.constants.ts

**Description**: Before the Documents type was not preselected and when it was preselected it threw an error saying "missing information" but now it adds the field code to the table successfully
**Before:** 
**After:**
**Pre-selected by default when document is selected:**
**Added successfully without throwing an error:**

Pre-selected Document Type Implementation

---

src/app/ats-guard.guard.ts
src/app/hris-guard.guard.ts

Previously, the solution had an issue with the environment.development variable causing logout to occur in a different environment. To address this, the PR removes the environment.development check and ensures consistent behavior regardless of the environment.
An attempt to fix this issue was submitted Previously here:
[ Bug 8899 | Users with "Employee" Role get's logged out immediately (Solution 1)](https://github.com/RetroRabbit/RGO-Client/pull/420)
[Bug 8899 | Azure board](https://dev.azure.com/retro-rabbit/RetroGradOnboard/_sprints/taskboard/RetroGradOnboard%20Team/RetroGradOnboard/Sprint%2021?workitem=8899)

Bug 8899 | Users with "Employee" Role get's logged out immediately (Solution 2)

---

src/app/components/hris/employees/employee-profile/accordions/accordion-career-summary/accordion-certificates/accordion-certificates.component.ts

Removed flag causing the icons to disappear
After deleting the icons no longer dissapear

fixed add new bug causing icons to dissapear

---

src/app/components/hris/employees/employee-profile/accordions/accordion-documents/accordion-additional-documents/accordion-additional-documents.component.html
src/app/components/hris/employees/employee-profile/accordions/accordion-documents/accordion-additional-documents/accordion-additional-documents.component.ts

Description: When Documents are archived in system settings > Custom Field Management they are supposed to disappear on the accordion and when unarchived appear again on the accordion
**Archived Documents:**
**No Documents Displayed when custom documents is archived:**
**Custom Documents not archived:**
**Custom Document Field Showing when not archived:**

Custom documents archive

---

src/app/components/hris/employees/employee-profile/accordions/accordion-administrative-documents/accordion-administrative-documents.component.css
src/app/components/hris/employees/employee-profile/accordions/accordion-administrative-documents/accordion-administrative-documents.component.html
src/app/components/hris/employees/employee-profile/accordions/accordion-administrative-documents/accordion-administrative-documents.component.ts

**Updated the written approval of offer to accept more document types:**
- Added helper text like on the design:
- Uploaded PDF:
- Uploaded PNG:
- Uploaded JPG:
- When uploading the wrong file type:

Updated uploads to take in PDF, PNG and JPG with helper text

---

src/app/components/hris/employees/employee-profile/accordions/accordion-career-summary/accordion-career-work-experience/accordion-career-work-experience.component.html
src/app/components/hris/employees/employee-profile/accordions/accordion-career-summary/accordion-certificates/accordion-certificates.component.html

Workexperience and certificates accordion was showing save and cancel buttons when edit was clicked even if there were no forms to edit so i added a extra check to disable it if nothing has been saved

added extra checks

---

src/app/components/hris/employees/employee-profile/accordions/accordion-documents/accordion-additional-documents/accordion-additional-documents.component.html
src/app/components/hris/employees/employee-profile/accordions/accordion-documents/accordion-additional-documents/accordion-additional-documents.component.ts

Fixed duplication bug where documents where rendering twice

fixed duplication bug

---

src/app/components/hris/employees/employee-profile/accordions/accordion-career-summary/accordion-career-work-experience/accordion-career-work-experience.component.css
src/app/components/hris/employees/employee-profile/accordions/accordion-career-summary/accordion-career-work-experience/accordion-career-work-experience.component.html

- Updated the delete to be a button and aligned with the designs
- Also added the horizontal line to separate the forms for better distinction
- Date has also been added in previous ticket but now it is not being overwritten by the delete and both are displayed
- Small styling changes
**Previous:**
**Currently:**

Delete button update - work experience

---

src/app/components/hris/employees/employee-profile/accordions/accordion-career-summary/accordion-career-summary-qualifications/accordion-career-summary-qualifications.component.ts

Fixed a object object error that was being throw when you try and save the qualifications accordion without uploading a doc
- Snackbar now clarifies that you need a document or you need to fill in missing fields depending on the situation

fixed object object error

---

src/app/components/hris/employees/employee-profile/accordions/accordion-career-summary/accordion-career-work-experience/accordion-career-work-experience.component.css
src/app/components/hris/employees/employee-profile/accordions/accordion-career-summary/accordion-career-work-experience/accordion-career-work-experience.component.html
src/app/components/hris/employees/employee-profile/accordions/accordion-career-summary/accordion-certificates/accordion-certificates.component.css
src/app/components/hris/employees/employee-profile/accordions/accordion-career-summary/accordion-certificates/accordion-certificates.component.html

_**Ticket Details:**_
- Updated the styling and implemented the design for delete buttons from Figma
- Added lines under forms to be able to distinguish between forms
- (This has been implemented for both Work Experience and Certificate accordions)
1. **Certificates Accordion:**
2. **Work Experience Accordion:**
_**Tested this and it works on other employees as well:**_

Updated the delete buttons and form design for Work Experience and Certification accordions

---

src/app/components/hris/employees/employee-profile/shared-accordion-functionality.ts

Home number is not a required field so it no longer throws missing info if it s not filled in
The contact and address details now only show missing information if a required field is missing data

Juanro/fix required missing info 

---

src/app/components/hris/employees/employee-profile/accordions/accordion-career-summary/accordion-career-summary-qualifications/accordion-career-summary-qualifications.component.ts
src/app/components/hris/employees/employee-profile/accordions/accordion-career-summary/accordion-career-work-experience/accordion-career-work-experience.component.ts
src/app/components/hris/employees/employee-profile/accordions/accordion-career-summary/accordion-certificates/accordion-certificates.component.html
src/app/components/hris/employees/employee-profile/accordions/accordion-career-summary/accordion-certificates/accordion-certificates.component.ts
src/app/components/hris/employees/employee-profile/shared-accordion-functionality.ts

The bug that was fixed: Career progress would go into  "**Infinity**" and progress calculation would run over **100%.**
Description of Fix: Career progress works perfectly for all accordions and updates the overall progress as well.
**Work experience and certificates is empty:**
**One of the accordions are empty:**

Career summary progress Bug Fix

---

src/app/components/hris/employees/new-employee/new-employee.component.html
src/app/components/hris/employees/new-employee/new-employee.component.ts

- Fixed validation for file drop now only allows pdf

added validation for starter kit document upload

---

src/app/components/ats/candidates/new-candidate/new-candidate.component.ts
src/app/components/hris/employees/new-employee/new-employee.component.ts

**Details:**
- Cant see the default profile image when creating a new employee.
**Fixed:**
- When you create a new employee you can now see the default profile image
- Made the TBA string empty because of the check for the image upload which causes issues

Default profile image loaded when creating new employee

---

src/app/components/hris/nav-bar/types/top-nav/top-nav.component.ts

**9516 DEV | Employee role should not request to get all charts** 
This fix restricts employee role from requesting all charts.
[Azure bug](https://dev.azure.com/retro-rabbit/RetroGradOnboard/_sprints/taskboard/RetroGradOnboard%20Team/RetroGradOnboard/Sprint%2023?workitem=9516)

9516 DEV | Employee role should not request to get all charts 

---

src/app/components/hris/employees/view-employee/view-employee.component.html

- Add Alignment on the Employee Table is wonky when Roles are hidden

 Employee Table

---

src/app/components/hris/employees/view-employee/view-employee.component.css
src/app/components/hris/employees/view-employee/view-employee.component.html

fixed color and spacing

---

src/app/components/hris/employees/employee-profile/accordions/accordion-career-summary/accordion-certificates/accordion-certificates.component.html
src/app/components/hris/employees/employee-profile/accordions/accordion-career-summary/accordion-certificates/accordion-certificates.component.ts

Description: Users should not be allowed to input dates that are in the future because the certificate would only be issued to the employee upon completion.

UI Styling Fix in Certificates Accordion

---

src/app/components/hris/employees/employee-profile/accordions/accordion-career-summary/accordion-career-work-experience/accordion-career-work-experience.component.ts
src/app/components/hris/employees/employee-profile/accordions/accordion-career-summary/accordion-certificates/accordion-certificates.component.ts
src/app/components/hris/employees/employee-profile/shared-accordion-functionality.ts

Career progress calculation updated: removed calculation for accordions with no required fields. Only accordions with required fields are calculated.
Error shows only on required accordions:

Fixed Career Summary Percentage
